### PR TITLE
Split NodeJS and browser setup

### PR DESCRIPTION
**Pull request by dapplion**
Should be merged with https://github.com/herumi/bls/pull/65

----

Splits module initialization logic from BLS wrapper logic
- `bls.js` setup logic is reduced to 3 lines using the `createBlsModule` function exported by `bls_c.js`. If https://github.com/herumi/bls/pull/65 is merged `createBlsModule` returns an already initialized Module with the WASM source thanks to inlining.
- The NodeJS and browser specific logic is splited into `index.js` for NodeJS and `bls-demo.js`. External library consumers can use `index.js` just as they did before with `bls.js`. The `bls-demo.html` demo site works as before.

### CODE REVIEW

**Review by wemeetagain — APPROVED** [review]

**Comment by herumi** [comment]
Thank you for the PR.
But your patch does not pass the test https://travis-ci.org/github/herumi/bls-eth-wasm/builds/739669483 .
Did the way of the test been changed?

**Comment by herumi** [comment]
I'm sorry that I missed https://github.com/herumi/bls/pull/65 . I'll check it again.

**Comment by dapplion** [comment]
> I'm sorry that I missed [herumi/bls#65](https://github.com/herumi/bls/pull/65) . I'll check it again.

@herumi This PR assumes that the wasm file is inlined in `bls_c.js` otherwise the test would fail.

**Comment by dapplion** [comment]
@herumi I've rebase this branch & PR on your dev branch after you've merged https://github.com/herumi/bls/pull/65. Now you can run 
```
node test.js
```
and it should work fine

**Comment by herumi** [comment]
I have one question.
Is it standard way to require not `bls.js` but `index.js`?
This modification breaks backward compatibility.

**Comment by dapplion** [comment]
> I have one question.
> Is it standard way to require not `bls.js` but `index.js`?
> This modification breaks backward compatibility.

Yes, it is standard for `index.js` to be the entry point of a library. I also created `index.js` to prevent an unnecessary big diff in this PR.

**Comment by herumi** [comment]
Many thanks. I have a fews day off now. I'll check it later.

**Comment by dapplion** [comment]
> Many thanks. I have a fews day off now. I'll check it later.

I've pushed a commit to prevent breaking changes. If you prefer to have index.js as the entry point you can revert the last commit. Let me know if you have any more questions

**Comment by herumi** [comment]
Your advice is very helpful. Many thanks.
I use `index.js` instead of `bls.js`.

**Comment by herumi** [comment]
May I move setup for browser into bls.js?
https://github.com/herumi/bls-eth-wasm/commit/e9130b9808cbe55dbac127fff470b23e73e68873

**Comment by dapplion** [comment]
> May I move setup for browser into bls.js?
> [e9130b9](https://github.com/herumi/bls-eth-wasm/commit/e9130b9808cbe55dbac127fff470b23e73e68873)
> 
> If it is not the standard way, then I'll revert it.

Usually, web developers use bundling tools such as [webpack](https://webpack.js.org/) which bundle all javascript code into a single file. In a similar fashion to emcc inlining the wasm file to bls_c.js. So usually the standard way is to not have code to inject global state the browser global window object. However, for the sake of simplicity in your .HTML example adding browser window injection code prevents having to add webpack to the project.

**Comment by herumi** [comment]
I'm now studying webpack and babel, etc. Please wait for a moment.

**Comment by dapplion** [comment]
> I'm now studying webpack and babel, etc. Please wait for a moment.

If you need help in your study with a direct chat, please don't hesitate to say hi at our discord server https://discord.gg/QpMMT6Z3

**Comment by herumi** [comment]
@dapplion 
Thank you for helping me.

I'm sorry that your discord url is expored.

I'm studying webpack and writing a sample code.
https://github.com/herumi/misc/tree/master/webpack/test2

In `test2/src`,

`make` makes add_c.js and `node test.js` runs well.
But in `test2/`,

`make` causes an error.

>ERROR in ./src/add_c.js 71:20-43
>Module not found: Error: Can't resolve 'path' in '/home/shigeo/Program/misc/webpack/test2/src'

```
if (ENVIRONMENT_IS_NODE) {
 if (ENVIRONMENT_IS_WORKER) {
  scriptDirectory = require("path").dirname(scriptDirectory) + "/";
 } else {
  scriptDirectory = __dirname + "/";
 }
 read_ = function shell_read(filename, binary) {
  var ret = tryParseAsDataURI(filename);
  if (ret) {
   return binary ? ret : ret.toString();
  }
  if (!nodeFS) nodeFS = require("fs");
  if (!nodePath) nodePath = require("path");
  filename = nodePath["normalize"](filename);
  return nodeFS["readFileSync"](filename, binary ? null : "utf8");
...
```
in src/add_c.js, `require` is not called, so I comment out these `require`, then
`make` makes `test2/index.js` but `node test-webpack.js` causes an error.

Could you give me some advice?

**Comment by dapplion** [comment]
@herumi The discord invite URL is public, don't worry.

EMCC adds nodejs code which webpack fails to resolve because it's targeting the browser https://github.com/webpack-contrib/css-loader/issues/447. To fix it set the target to node
```js
// webpack.config.js
module.exports = {
  target: "node",
};
```
Note: If you name the config file `webpack.config.js` it will be detected automatically without needing the --config option.

**Comment by herumi** [comment]
That's very kind of you.
I can run a sample for Node.js and brower.
https://github.com/herumi/misc/blob/master/webpack/test2/webpack.config.js
But I have to change the target for them. Can I make `index.js` which supports both Node.js and browser like the current `bls.js`?

**Comment by herumi** [comment]
I modified:
- blsSetupFactory can be local https://github.com/herumi/bls-eth-wasm/commit/6523eb0ea922ff9f70f13554355739bf03d2d8bf
- rename createBlsModule to blsCreateModule https://github.com/herumi/bls-eth-wasm/commit/3457afd2003eb268316878566e795d6d26d6b9f0

I tried `bls-eth-wasm` in React, then `bls` is not visible.
So I added `window.bls = bls` https://github.com/herumi/bls-eth-wasm/commit/08dacb940ceff791036eb8ed048041f523ddaefa
I think that it is bad way. Is there any good way?

**Comment by dapplion** [comment]
> That's very kind of you.
> I can run a sample for Node.js and brower.
> https://github.com/herumi/misc/blob/master/webpack/test2/webpack.config.js
> But I have to change the target for them. Can I make `index.js` which supports both Node.js and browser like the current `bls.js`?

You as developer of the library won't use webpack to distribute the library. Instead, consumers of the library will use webpack, mainly front-end developers. I would structure the repo as
```
/
├── src
│   ├── bls.js
│   └── index.js
├── browser-demo
│   ├── demo.html
│   ├── demo.js
│   └── webpack.config.js
└── nodejs-demo
    └── demo.js
```
So in case someone wants to use webpack for NodeJS they can use a different webpack configuration

**Comment by dapplion** [comment]
> I modified:
> 
> * blsSetupFactory can be local [6523eb0](https://github.com/herumi/bls-eth-wasm/commit/6523eb0ea922ff9f70f13554355739bf03d2d8bf)
> * rename createBlsModule to blsCreateModule [3457afd](https://github.com/herumi/bls-eth-wasm/commit/3457afd2003eb268316878566e795d6d26d6b9f0)
> 
> I tried `bls-eth-wasm` in React, then `bls` is not visible.
> So I added `window.bls = bls` [08dacb9](https://github.com/herumi/bls-eth-wasm/commit/08dacb940ceff791036eb8ed048041f523ddaefa)
> I think that it is bad way. Is there any good way?

I've created a setup with webpack with your browser demo. It uses vanilla js, but I can add React if you want to see how that would work.
https://github.com/herumi/bls-eth-wasm/pull/7

**Comment by herumi** [comment]
It sounds good.
I wanted a static HTML demo, so I modified it a bit.

**Comment by dapplion** [comment]
> It sounds good.
> I wanted a static HTML demo, so I modified it a bit.

I have to say adding `<script>window.module = {}</script>` at the top of the static HTML file is very creative. 

However, you can showcase your library on Github pages https://pages.github.com/ which would allow you greater flexibility.

For the browser-demo, committing the package-lock.json is recommended. You can read more about it here https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json

**Comment by herumi** [comment]
Thank you for all the advice.
>Such as splitting bls.js in more than one file, or writing it with Typescipt

You are right. But I'm not a frontend engineer and I have many tasks and I can't spend a lot of time to study it.
Please wait a moment until I study TypeScript.

>For the browser-demo, committing the package-lock.json is recommended.

I see.

**Comment by herumi** [comment]
I've removed `EXPORT_NAME` option because it seems unnecessary to create a module.
https://github.com/herumi/bls-eth-wasm/commit/9cdd2ef0af9080a87c6233e3067446431b661fab#diff-3e2513390df543315686d7c85bd901ca9256268970032298815d2f893a9f0685

**Comment by dapplion** [comment]
While EXPORT_NAME is not mandatoey it's use is recommended in the emcc docs. Since it's available in the global window object there can be naming collisions if someone uses more than one wasm factories within the same website

**Comment by herumi** [comment]
Thanks for your advice.
As you say, I think that it is better to avoid global naming collisions and I do not know the drawback without EXPORT_NAME now, so I'll do without EXPORT_NAME unless some problem happens.

**Pull request closed without merging**
